name: glamify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.6
  cryptography: ^2.7.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lucide_icons: ^0.256.0
  random_string: ^2.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.5

flutter_native_splash:
  color: "#000000"
  image: assets/images/glamify_logo.jpg
  color_dark: "#000000"
  image_dark: assets/images/glamify_logo.jpg

  android_12:
    image: assets/images/glamify_logo.jpg
    icon_background_color: "#000000"
    image_dark: assets/images/glamify_logo.jpg
    icon_background_color_dark: "#000000"
  fullscreen: true
  web: true

 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/glamify_logo.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0xFF"
  adaptive_icon_foreground: "assets/images/glamify_logo_foreground.png"
  web:
    generate: true
    image_path: "assets/images/glamify_logo.png"
    background_color: "0xFF"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/glamify_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/glamify_logo.png"



flutter:
  uses-material-design: true
  assets:
    - ./assets/images/
