name: glamify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.6
  cryptography: ^2.7.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  lucide_icons: ^0.256.0
  random_string: ^2.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.5

flutter_native_splash:
  # use your sampled background color!
  color: "#191B06"
  image: assets/images/glamify_logo.png
  fullscreen: true

  android_12:
    # this config is for the new Android‑12 splash API
    color: "#191B06"
    image: assets/images/glamify_logo.png
    icon_background_color: "#191B06"
    fullscreen: true

  ios: true
  android: true
  web: true
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/glamify_logo.png"   # fallback on older platforms
  adaptive_icon_background: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"

  web:
    generate: true
    image_path: "assets/images/ic_launcher_foreground.png"
    background_color: "#191B06"
    theme_color: "#191B06"

  windows:
    generate: true
    image_path: "assets/images/ic_launcher_foreground.png"
    background_color: "#191B06"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/images/ic_launcher_foreground.png"
    background_color: "#191B06"



flutter:
  uses-material-design: true
  assets:
    - ./assets/images/
