// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTCBRTlR3XExS2VFp2cSpBG4eDLmh9Ww',
    appId: '1:857868964979:web:5d78740102c5f2f9a10606',
    messagingSenderId: '857868964979',
    projectId: 'tryglamify',
    authDomain: 'tryglamify.firebaseapp.com',
    storageBucket: 'tryglamify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxivBz1cEdd00mmPEKCfJfj6FdkJi7HdM',
    appId: '1:857868964979:android:3e7f0f353246c9b2a10606',
    messagingSenderId: '857868964979',
    projectId: 'tryglamify',
    storageBucket: 'tryglamify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1mVgZbKxnh45CgQMnfP6a7xlwov-ZrZo',
    appId: '1:857868964979:ios:c19697ef400b8805a10606',
    messagingSenderId: '857868964979',
    projectId: 'tryglamify',
    storageBucket: 'tryglamify.firebasestorage.app',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1mVgZbKxnh45CgQMnfP6a7xlwov-ZrZo',
    appId: '1:857868964979:ios:c19697ef400b8805a10606',
    messagingSenderId: '857868964979',
    projectId: 'tryglamify',
    storageBucket: 'tryglamify.firebasestorage.app',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTCBRTlR3XExS2VFp2cSpBG4eDLmh9Ww',
    appId: '1:857868964979:web:32e62ca0d43ce235a10606',
    messagingSenderId: '857868964979',
    projectId: 'tryglamify',
    authDomain: 'tryglamify.firebaseapp.com',
    storageBucket: 'tryglamify.firebasestorage.app',
  );
}
