// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhW_V0itlbvj3H1yn_8ZS0boc3I91Ous',
    appId: '1:916297689274:web:cf1328dbefb7849fb3fa83',
    messagingSenderId: '916297689274',
    projectId: 'glamify-ef52b',
    authDomain: 'glamify-ef52b.firebaseapp.com',
    storageBucket: 'glamify-ef52b.firebasestorage.app',
    measurementId: 'G-DY62CTE1J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNiOvxKyEIXj4c49cjAAK-9Brvl8CHkOU',
    appId: '1:916297689274:android:31630a00afcc0854b3fa83',
    messagingSenderId: '916297689274',
    projectId: 'glamify-ef52b',
    storageBucket: 'glamify-ef52b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXg4AXhcuHbL6_4ELNaeFk75UwfZTTtjg',
    appId: '1:916297689274:ios:a7d7f610597be28cb3fa83',
    messagingSenderId: '916297689274',
    projectId: 'glamify-ef52b',
    storageBucket: 'glamify-ef52b.firebasestorage.app',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXg4AXhcuHbL6_4ELNaeFk75UwfZTTtjg',
    appId: '1:916297689274:ios:a7d7f610597be28cb3fa83',
    messagingSenderId: '916297689274',
    projectId: 'glamify-ef52b',
    storageBucket: 'glamify-ef52b.firebasestorage.app',
    iosBundleId: 'com.example.glamify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhW_V0itlbvj3H1yn_8ZS0boc3I91Ous',
    appId: '1:916297689274:web:0e5000e196adf298b3fa83',
    messagingSenderId: '916297689274',
    projectId: 'glamify-ef52b',
    authDomain: 'glamify-ef52b.firebaseapp.com',
    storageBucket: 'glamify-ef52b.firebasestorage.app',
    measurementId: 'G-1GJE41LF3D',
  );
}
